#!/bin/bash

# Filename: ~/github/dotfiles-latest/sketchybar/felixkratz/sketchybarrc

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items"     # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

# Needs to have Regular, Bold, Semibold, Heavy and Black variants
# FONT="SF Pro"
FONT="MesloLGM Nerd Font"

# All paddings use this value (icon, label, background), default is 3 but I
# decreased it
PADDINGS=1

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
	height=49
	color=$BAR_COLOR
	border_width=2
	border_color=$BAR_BORDER_COLOR
	shadow=off
	position=top
	sticky=on
	padding_right=10
	padding_left=10
	y_offset=-5
	margin=-2
	topmost=window
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
	updates=when_shown
	icon.font="$FONT:Bold:14.0"
	icon.color=$ICON_COLOR
	icon.padding_left=$PADDINGS
	icon.padding_right=$PADDINGS
	label.font="$FONT:Semibold:13.0"
	label.color=$LABEL_COLOR
	label.padding_left=$PADDINGS
	label.padding_right=$PADDINGS
	padding_right=$PADDINGS
	padding_left=$PADDINGS
	background.height=26
	background.corner_radius=9
	background.border_width=2
	popup.background.border_width=2
	popup.background.corner_radius=10
	popup.background.border_color=$POPUP_BORDER_COLOR
	popup.background.color=$POPUP_BACKGROUND_COLOR
	popup.blur_radius=20
	popup.background.shadow.drawing=on
	scroll_texts=on
)

sketchybar --default "${defaults[@]}"

###############################################################################
#                                Left side
###############################################################################

# Shows the apple logo, you can change it's color in "items/apple.sh"
# If you click on it, you can see preferences, activity and lock screen
source "$ITEM_DIR/apple.sh"

source "$PLUGIN_DIR/aerospace.sh"


# Shows the name and icon of the app currently focused
# Clicking it opens mission control (can be customized)
# source "$ITEM_DIR/front_app.sh"

###############################################################################
#                                 Center
###############################################################################

# Shows album art and song name, I prefer this as it give me useful info
# source "$ITEM_DIR/media.sh"


###############################################################################
#                               Right side
###############################################################################

# If calendar is clicked, will run zen.sh which hides everything, but you can
# customize it to your liking
source "$ITEM_DIR/calendar.sh"

# Shows the SSID you're connected to, and the IP address assigned
source "$ITEM_DIR/wifi.sh"

# By default the icon will only show when on battery and if it's 50% or less,
# you can change "plugins/battery.sh" if needed to modify the behavior
source "$ITEM_DIR/battery.sh"

# left click to change volume
# right click to switch audio sources, you need switchaudio-osx
source "$ITEM_DIR/volume.sh"

# CPU usage indicator
source "$ITEM_DIR/cpu.sh"


##### VPN ####
# sketchybar --add item vpn right
# sketchybar --set vpn \
#   script="$PLUGIN_DIR/vpn.sh" \
#   update_freq=10 \
#   label.font="Hack Nerd Font:Bold:12.0" \
#   label.padding_left=10 \
#   icon.padding_left=10 \
#   icon.font="Hack Nerd Font:Bold:12.0" \
#   label.color=0xffdcdfe4 \
#   icon.color=0xffa3be8c


# Add the first separator icon
sketchybar --add item separator_icon1 right
sketchybar --set separator_icon1 \
    icon=• \
    icon.color=0xffd08770 \
    icon.padding_left=5 \
    icon.padding_right=5

# Add a right-side item for disk usage
sketchybar --add item disk_usage right
sketchybar --set disk_usage \
    script="$PLUGIN_DIR/disk.sh" \
    update_freq=60 \
    padding_left=5 \
    padding_right=5

# Add the second separator icon
sketchybar --add item separator_icon2 right
sketchybar --set separator_icon2 \
    icon=• \
    icon.color=0xffd08770 \
    icon.padding_left=5 \
    icon.padding_right=5

# Add Docker status item
sketchybar --add item docker.status right
sketchybar --set docker.status \
    icon.font="Hack Nerd Font:Bold:14.0" \
    label="Docker [0]" \
    update_freq=10 \
    padding_left=10 \
    padding_right=10 \
    script="$PLUGIN_DIR/docker.sh" \
    click_script="$PLUGIN_DIR/docker.sh"


# Add the second separator icon
sketchybar --add item separator_icon3 right
sketchybar --set separator_icon3 \
    icon=• \
    icon.color=0xffd08770 \
    icon.padding_left=5 \
    icon.padding_right=5

###############################################################################
#                            Community plugins
###############################################################################

# Community plugin that I modified, so that it shows you the mic name
# If you right click it you can change the mic.
# Shows you the value of the input volume level
#source "$ITEM_DIR/mic.sh"

###############################################################################

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
